# config.yaml

#SRA
sra_toolkit: "/SAN/vyplab/alb_projects/tools/sratoolkit.3.1.1-centos_linux64/bin/"
samples_csv: "samples.csv"
sra_column: run   
end_type: pe              # 'se' = single-end, 'pe' = paired-end
use_local_fastq: false     # assuming you're not using pre-downloaded FASTQ

#FASTP
fastp_length: 40

#STAR - human
url_genomefasta_human: "ftp://ftp.ebi.ac.uk/pub/databases/gencode/Gencode_human/release_44/GRCh38.p14.genome.fa.gz"
output_name_genomefasta_human: "/SAN/vyplab/NYGC_ALSFTD/RIMOD_FTD/VIRTUS2/virtus_work/human.fasta"
dir_name_star_human: "/SAN/vyplab/NYGC_ALSFTD/RIMOD_FTD/VIRTUS2/virtus_work/STAR_index_human/"
outFileNamePrefix_human: "human"

#STAR - virus
url_virus: "https://raw.githubusercontent.com/yyoshiaki/VIRTUS2/master/data/viruses.fasta"
output_name_virus: "/SAN/vyplab/NYGC_ALSFTD/RIMOD_FTD/VIRTUS2/virtus_work/virus.fasta"
dir_name_star_virus: "/SAN/vyplab/NYGC_ALSFTD/RIMOD_FTD/VIRTUS2/virtus_work/STAR_index_virus/"

# Processing parameters
threads: 8
genomesa_nbases_virus: 12
genomesa_nbases_human: 14

# Singularity containers (optional override)
containers:
  star: "docker://quay.io/biocontainers/star:2.7.10a--h9ee0642_0"

# FINAL REPORT
filename_output: "VIRTUS.output.tsv"



